language: ruby
rvm:
- 2.4.1
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake --trace db:create
- RAILS_ENV=test bundle exec rake --trace db:migrate
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
- bundle exec rubocop --config .rubocop.yml
deploy:
  provider: heroku
  api_key:
    secure: b5deaAxz3M/b7sCz0NRpF9AIsY3EXnfKUnQ8vvlBfG4Ta3a0XKnF4gBmCA2d5jzaMqTw3MuSKNUF/z/5qEu5rSXwQgxUa1mIltuWtdYMufcmNkyb/2niJbmAULWl/XDY6vPxNVy+VFeaBCjSv3IDpcFw4H03P63qFW8qtDb8b3rcNzmMPUzEMELWvwewdvjLazYtFyl2zgTXUbdOK77hlFk8eZ8+dpnnOggcHiWG28DExQM9z/liko9ripjZFEc2R+V2dB8D662tVxr/UxMdZ0wFVgICir0n03fFnHHnnUSdLdOtEZ4UcnP11fzD08kPVxLqpu0g0lUs2JB8TNSfH8Qi1DlL56KuJbuVzrN8z/Xogze6tue+51yvlGFK3i4sPb5p5GexpsQLmPbf/Jwj8EwN/HcesLApxj48/C+LWDMhuQ2YNyh9ovGGz7+RnRMYur4Q9lHJnxRfw8/TOvN6MwKqit4sWtraoG8muU/dPOmfsozhYfPLnmRGI7zpx5aEEDh19VCpXiOEVPjlG4y7yVXSjdcXVUfOXCb+BTfzPhfCN4JX9ZY2KL+g5avYQzeNQ/QfltUulrBQ5e/SVIJucbHy7Cj88F71EeYsRB9p/ofP3V+pTOezQ1zM6sgUEDW/BmH0BkOgh7D7LMVgV2mFYpw4KaUqXiN04O2GFwEPYfQ=
    app: chessapp-fhp-tp
